version: 0.3.0.{build}
image: Visual Studio 2017
configuration: Release
platform: Any CPU

environment:
  PFX_PASSWORD:
    secure: wB19redOwiER/t000/oJpCZEu41oxfSlcBuVUNaILO0=

assembly_info:
  patch: true
  file: '**\AssemblyInfo.cs'
  assembly_version: $(appveyor_build_version)
  assembly_file_version: $(appveyor_build_version)
  assembly_informational_version: $(appveyor_build_version)

before_build:
- cmd: nuget restore
- cmd: nuget install -ExcludeVersion ILMerge
- ps: Import-PfxCertificate -FilePath EliteLogAgent\code-signing.pfx -CertStoreLocation Cert:\CurrentUser\My -Password $(ConvertTo-SecureString "$env:PFX_PASSWORD" -AsPlainText -Force)

after_build:
- cmd: msbuild Elite-Log-Agent.sln /verbosity:minimal /m /target:Publish /p:Configuration=Release /p:Platform="Any CPU" /p:PublishProfile=Release /property:ApplicationVersion=%APPVEYOR_BUILD_VERSION%
- cmd: ILMerge\tools\ilmerge.exe /wildcards /out:EliteLogAgent.exe EliteLogAgent\bin\Release\EliteLogAgent.exe EliteLogAgent\bin\Release\*.dll

artifacts: 
- path: EliteLogAgent.exe
  name: single-executable
- path: EliteLogAgent\bin\Release\app.publish
  name: clickonce-files

deploy:
- provider: GitHub
  on:
    branch: develop
  tag: release-$(appveyor_build_version)
  release: $(appveyor_build_version)
  auth_token:
    secure: cMLUYhjbQt3D197vZwjRci/zvwagN86wEZtJzX1L3apKsslN44Uo6TUo54vIQVg6
  artifact: single-executable
  draft: true
  prerelease: true
  force_update: true

- provider: AzureBlob
  on:
    branch: master
  artifact: clickonce-files
  storage_account_name: elitelogagent
  container: clickonce
  unzip: true
  storage_access_key:
    secure: QG+FUaRxa8VX+7XDNhCX/XLHv+G/2PyACt8POHWNVOKm9jgT4/1WCYNfsTHdsXMrZyDh77uDw68ulHtz7i/AREoNxu1y9Z5ZD+nrDL6/R8TwCDljhq9S+EUusNk3CCMZ
